# Generated by Django 2.2.5 on 2019-10-01 03:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300, verbose_name='Название продукта')),
                ('description', models.CharField(max_length=500, null=True, verbose_name='Описание продукта')),
                ('price', models.FloatField(null=True, verbose_name='Цена продукта')),
                ('image', models.ImageField(upload_to='', verbose_name='Изображение')),
                ('avaliabled', models.BooleanField(default=True, verbose_name='Отображать на сайте')),
            ],
            options={
                'verbose_name': 'Продукт',
                'verbose_name_plural': 'Продукты',
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Имя заказчика')),
                ('phone', models.CharField(max_length=20, verbose_name='Телефон')),
                ('email', models.CharField(max_length=50, verbose_name='Email')),
                ('products', models.ManyToManyField(blank=True, null=True, related_name='product', to='core.Product', verbose_name='Продукты заказа')),
            ],
            options={
                'verbose_name': 'Заказ',
                'verbose_name_plural': 'Заказы',
            },
        ),
    ]
